#ifndef SH_AVPS_H
#define	SH_AVPS_H


#define		SH_AVP_CODE_USER_IDENTITY			700
#define		SH_AVP_CODE_MSISDN					701
#define		SH_AVP_CODE_USER_DATA				702
#define		SH_AVP_CODE_DATA_REFERENCE			703
#define		SH_AVP_CODE_SERVICE_INDICATION		704
#define		SH_AVP_CODE_SUBS_REQ_TYPE			705
#define		SH_AVP_CODE_REQUESTED_DOMAIN		706
#define		SH_AVP_CODE_CURRENT_LOCATION		707
#define		SH_AVP_CODE_IDENTITY_SET			708
#define		SH_AVP_CODE_EXPIRY_TIME				709
#define		SH_AVP_CODE_SEND_DATA_INDICATION	710
#define		SH_AVP_CODE_SERVER_NAME				602
#define		SH_AVP_CODE_SUPPORTED_FEATURES		628
#define		SH_AVP_CODE_FEATURE_LIST_ID			629
#define		SH_AVP_CODE_FEATURE_LIST 			630
#define		SH_AVP_CODE_SUPPORTED_APPLICATIONS	631
#define		SH_AVP_CODE_PUBLIC_IDENTITY			601
#define		SH_AVP_CODE_DSAI_TAG				711
#define		SH_AVP_CODE_WILDCARDED_PSI			634

#endif //#ifndef SH_AVPS_H
