#ifndef DB_SH_QUERYCODES_H
#define DB_SH_QUERYCODES_H



#define	DB_SH_QUERY_UDR_ALIASES_REPO_DATA_BY_PUI					1
#define	DB_SH_QUERY_UDR_CHARGING_INFO_BY_PUI						2
#define	DB_SH_QUERY_UDR_DSAI_BY_PSI									3
#define	DB_SH_QUERY_UDR_DSAI_BY_PUI									4
#define	DB_SH_QUERY_UDR_IFC_BY_PSI									5
#define	DB_SH_QUERY_UDR_IFC_BY_PUI									6
#define	DB_SH_QUERY_UDR_IMS_USER_STATE_BY_PUI						7
#define	DB_SH_QUERY_UDR_PSI_ACTIV_BY_PSI							8
#define	DB_SH_QUERY_UDR_REPO_DATA_BY_PUI							9
#define	DB_SH_QUERY_UDR_SCSCFNAME_BY_PSI							10
#define	DB_SH_QUERY_UDR_SCSCFNAME_BY_PUI							11
#define	DB_SH_QUERY_PUR_UPDATE_ALIAS_REPO_DATA						12
#define	DB_SH_QUERY_PUR_GET_DATAEXTID_BY_PSI						13
#define	DB_SH_QUERY_PUR_GET_REPOID_BY_PUI_AND_SRV_IND				14
#define	DB_SH_QUERY_PUR_GET_TDSI_ID_AND_DSAI_INFO_BY_PSI			15
#define	DB_SH_QUERY_PUR_GET_TDSI_ID_AND_DSAI_INFO_BY_PUI			16
#define	DB_SH_QUERY_PUR_GET_REPOID_BY_PSI_AND_SRV_IND				17
#define	DB_SH_QUERY_PUR_UPDATE_DSAI_BY_TDSI_ID						18
#define	DB_SH_QUERY_PUR_UPD_PSI_ACT_BY_DATAEXID						19
#define	DB_SH_QUERY_SH_GET_IDENTITY_TYPE							20
#define	DB_SH_QUERY_SH_GET_APSRV_ID_FROM_AS_ADR						21
#define	DB_SH_QUERY_SH_GET_APSRV_PERM_FROM_ASID 					22
#define	DB_SH_QUERY_UDR_GET_CHARGING_INFO_BY_PSI	 				23
#define	DB_SH_QUERY_UDR_GET_REPO_DATA_BY_PSI						24
#define	DB_SH_QUERY_SH_GET_PRIV_ID_FOR_PUB_ID						25
#define	DB_SH_QUERY_SH_GET_PUB_ID_FOR_PRIV_ID						26
#define	DB_SH_QUERY_SH_GET_REG_STATUS_FOR_PUI						27
#define	DB_SH_QUERY_SH_GET_BARR_INDIC_FOR_PUI						28
#define	DB_SH_QUERY_SH_PUR_DEL_REPO_DATA_REC_BY_PUI_SRV_IND			29
#define	DB_SH_QUERY_SH_PUR_INSERT_REC_INTO_REPO_DATA				30
#define	DB_SH_QUERY_SH_PUR_DEL_REPO_DATA_REC_BY_REPOID				31
#define	DB_SH_QUERY_SH_GET_PSI_ID_FOR_PUB_ID						32
#define	DB_SH_QUERY_SH_GET_PUB_ID_FOR_PSI_ID						33



#endif //#ifndef DB_SH_QUERYCODES_H
